### ISSUE TITLE
Ingredients with different units

### ISSUE THREAD

**Issue by jschirrmacher** [jschirrmacher/homagix#26]
Some ingredients use different units, depending if they are used in recipes or when contained in a shopping list.
For example, if you use 4 leaves of toast in your recipe, you will likely buy a whole toast bread.

To implement that, we can add a new part to the ingredient definition files which could look like this:

```yaml
---
id: 4f0c3a3c-f687-4641-a45a-d3f74eadc95a
name: Toast bread
unit: Leaves
packaging:
  unit: Pkg
  amount: 20
group: breakfast
```

The `amount` field means, that 20 leaves are contained in the package.

In the application, when collecting recipe ingredients, we need to add the original units and calculate (and print out) the resulting amount of packages we need to buy. If a recipe (for whatever reason) uses the packaging unit, the addition need to take that into account.

When adding more ingredients in the shopping list, both units should be offered.
